"""news radar

Revision ID: 0011_news_radar
Revises: 0010_formal_sealing
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0011_news_radar'
down_revision: Union[str, Sequence[str], None] = '0010_formal_sealing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('api_key_env', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider_key', name='uq_llm_provider_key')
    )
    op.create_table('news_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('fingerprint', sa.String(length=500), nullable=False),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('ai_status', sa.String(length=30), nullable=False),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_event_workspace_id'), 'news_event', ['workspace_id'], unique=False)
    op.create_table('news_feed',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('feed_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('schedule', sa.String(length=60), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'feed_key', name='uq_news_feed_key')
    )
    op.create_table('news_event_company',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('company_label', sa.String(length=200), nullable=False),
    sa.Column('ticker_hint', sa.String(length=60), nullable=True),
    sa.Column('relevance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('impact', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed_by', sa.String(length=120), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['news_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'company_label', name='uq_news_event_company')
    )
    op.create_index(op.f('ix_news_event_company_event_id'), 'news_event_company', ['event_id'], unique=False)
    op.create_table('news_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('feed_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_text', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('company_hint', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_event.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['news_feed.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'content_hash', name='uq_news_item_hash')
    )
    op.create_index(op.f('ix_news_item_event_id'), 'news_item', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_item_event_id'), table_name='news_item')
    op.drop_table('news_item')
    op.drop_index(op.f('ix_news_event_company_event_id'), table_name='news_event_company')
    op.drop_table('news_event_company')
    op.drop_table('news_feed')
    op.drop_index(op.f('ix_news_event_workspace_id'), table_name='news_event')
    op.drop_table('news_event')
    op.drop_table('llm_provider')
    # ### end Alembic commands ###
