#!/usr/bin/env node
/* Local design-state checks only. No real file intake, APIs, model, or scoring. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),{chromium}=require(process.argv[2]||'playwright');
(async()=>{let browser;const checks=[],requests=[],errors=[];const executedAt=new Date().toISOString();try{
 browser=await chromium.launch({headless:true,chromiumSandbox:true,args:['--disable-gpu'],...(process.argv[3]?{executablePath:process.argv[3]}:{})});
 const ctx=await browser.newContext({viewport:{width:1440,height:900}});await ctx.route(/^https?:/,r=>{requests.push(r.request().url());return r.abort();});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.join(root,'prototype/intake.html'));
 const check=async(id,scenario,fn)=>{try{await fn();checks.push({id,scenario,status:'passed'});}catch(e){checks.push({id,scenario,status:'failed',error:e.message});throw e;}};
 const text=()=>page.locator('#intake-main').innerText();
 await check('PD-INTAKE-01','摘要与上游解读/系统等待、多来源分别表达',async()=>{assert.match(await text(),/原Agent解读/);assert.match(await text(),/尚无影响判断/);assert.match(await text(),/具体文章原文尚未取得/);assert.equal(await page.getByRole('button',{name:'阅读原文',exact:true}).count(),1);await page.getByRole('button',{name:'阅读原文',exact:true}).click();assert.equal(await page.locator('#intake-dialog').evaluate(d=>d.open),true);assert.match(await page.locator('#dialog-text').innerText(),/客户验收/);await page.getByRole('button',{name:'关闭',exact:true}).click();});
 await check('PD-INTAKE-02','来源入口不假装已取正文',async()=>{await page.getByRole('button',{name:'来源入口',exact:true}).click();assert.match(await page.locator('#dialog-text').innerText(),/具体原文尚未取得/);await page.keyboard.press('Escape');assert.equal(await page.locator('#intake-dialog').evaluate(d=>d.open),false);});
 await check('PD-INTAKE-03','没有来源网址仍可阅读',async()=>{await page.locator('#intake-case').selectOption('missing');assert.match(await text(),/暂无原文入口/);assert.match(await text(),/合成订单/);assert.equal(await page.getByRole('button',{name:'阅读原文',exact:true}).count(),0);});
 await check('PD-INTAKE-04','访谈未知发布时间与阅读星级',async()=>{await page.locator('#intake-case').selectOption('interview');assert.match(await text(),/发布时间未明确/);assert.match(await text(),/不是公司评分/);assert.match(await text(),/未当作新闻发布时间/);});
 await check('PD-INTAKE-05','无动态说明独立于事件',async()=>{await page.locator('#intake-case').selectOption('coverage');assert.match(await text(),/本次采集未发现重要更新/);assert.match(await text(),/不产生零影响事件/);});
 await check('PD-INTAKE-06','部分失败资料仍可阅读',async()=>{await page.locator('#intake-case').selectOption('partial');assert.match(await text(),/6条成功资料可以阅读，1条尚未解析/);assert.match(await text(),/A9:G9/);assert.match(await text(),/合成订单/);});
 for(const width of [1440,1280,390,430]){await check('PD-INTAKE-WIDTH-'+width,'五种状态布局宽度'+width,async()=>{await page.setViewportSize({width,height:900});for(const value of ['sources','missing','interview','coverage','partial']){await page.locator('#intake-case').selectOption(value);const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(size.scroll<=size.width+1,JSON.stringify(size));}});}
 await check('PD-INTAKE-07','键盘可操作与本地无外发',async()=>{await page.locator('#intake-case').selectOption('sources');await page.getByRole('button',{name:'阅读原文',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#intake-dialog').evaluate(d=>d.open),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#intake-dialog').evaluate(d=>d.open),false);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);});
 await page.setViewportSize({width:1440,height:900});await page.locator('#intake-case').selectOption('sources');await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(150);await page.screenshot({path:path.join(root,'review/design-detail/intake-desktop.png')});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(150);await page.screenshot({path:path.join(root,'review/design-detail/intake-mobile.png')});
 }catch(e){process.exitCode=1;console.error(e.message);}finally{if(browser)await browser.close();const hashes=Object.fromEntries(['prototype/intake.html','prototype/style.css','tools/verify_intake_prototype.cjs'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')]));fs.writeFileSync(path.join(root,'review/design-detail/intake-prototype-checks.json'),JSON.stringify({scope:'Synthetic local reading-state prototype only; NOT product T-44..49 acceptance',executed_at:executedAt,revision_at_run:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),status:process.exitCode?'failed':'passed',checks,source_sha256:hashes,external_requests:requests,console_errors:errors,not_run:['Actual spreadsheet parsing/DB/API/RBAC/scoring','Real user/real device UX acceptance']},null,2)+'\n');console.log(process.exitCode?'FAILED':'PASS',checks.length,'intake prototype checks');}})();
