/* Local design prototype. Fixed synthetic snapshots; no API, persistence or rule engine. */
'use strict';
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(text,tone='gray')=>`<span class="badge ${tone}">${esc(text)}</span>`;
const btn=(text,action,cls='secondary',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const notice=(title,body,tone='')=>`<div class="notice ${tone}"><div><strong>${title}</strong><p>${body}</p></div></div>`;
const header=(title,sub,actions='')=>`<div class="page-header"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;
const panel=(title,body,sub='',action='')=>`<section class="panel"><div class="panel-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${action}</div><div class="panel-body">${body}</div></section>`;
const link=(route,text)=>`<a href="#${route}">${text}</a>`;
const roles={viewer:['research.read'],researcher:['research.read','analysis.override','template.edit'],strategy_manager:['research.read','template.edit','template.publish','strategy.publish'],data_admin:['research.read','source.manage','job.retry','identity.manage','quality.correct'],system_admin:['role.assign','model.configure','audit.read','ops.read']};
roles.lead=[...new Set([...roles.researcher,...roles.strategy_manager])];
let state;
const initial=()=>({mode:'business',role:'lead',scenario:'normal',company:'a',tab:'timeline',market:'all',changeType:'all',query:'',watch:['a-a'],note:'',decisionKind:'impact',replacement:'-0.2',reason:'',judgmentStatus:'auto',generation:3,decisionOriginal:'+0.8',grade:'1',decisionRecords:{impact:{value:'+0.8',status:'auto',generation:3},rubric:{value:'3',status:'auto',generation:2},risk:{value:'已接受，目标仅SYN-H挂牌',status:'auto',generation:1}},templateAge:'90',eventMode:'enabled',templateDraft:false,templatePreview:false,templatePublished:false,strategyThreshold:'70',strategyPreview:false,strategyPublished:false,sourcePaused:false,imported:false,jobRecovered:false,roleChanges:false,correctionAdded:false});
state=initial();
const companies={a:{name:'示例制造',sector:'一般制造',quality:'72.0',coverage:'100%',securities:[{id:'a-a',name:'SYN-A',market:'A 股',currency:'CNY',v:'68.0',price:'12.40',state:'待评估 · 最后区间内',tone:'amber'},{id:'a-h',name:'SYN-H',market:'港股',currency:'HKD',v:'45.0',price:'18.60',state:'区间外',tone:'gray'}]},b:{name:'示例设备',sector:'一般制造',quality:'76.0',coverage:'100%',securities:[{id:'b-a',name:'SYN-B',market:'A 股',currency:'CNY',v:'64.0',price:'16.20',state:'待入选 1/2',tone:'blue'}]}};
companies.a.dimensions=[['profit_quality','盈利质量','76.0','0.35'],['financial_resilience','财务韧性','75.0','0.20'],['business_model','商业模式','70.0','0.25'],['governance','治理与资本配置','65.0','0.15'],['growth_sustainability','成长持续性','63.0','0.05']];
companies.b.dimensions=[['profit_quality','盈利质量','80.0','0.30'],['financial_resilience','财务韧性','78.0','0.20'],['business_model','商业模式','74.0','0.25'],['governance','治理与资本配置','72.0','0.15'],['growth_sustainability','成长持续性','71.0','0.10']];
const changes=[{id:'enter',type:'ENTER',label:'新入选',tone:'green',company:'a',security:'SYN-A',market:'a',date:'09-29',title:'两个相邻收盘时点评估均满足入选条件',body:'经营分 72.0，估值分 68.0；规则与证据已固定。'}, {id:'risk',type:'RISK',label:'挂牌风险',tone:'red',company:'a',security:'SYN-H',market:'h',date:'09-30',title:'合成H挂牌退市决定，作用于这只挂牌证券',body:'SYN-A 不受该挂牌风险影响；H证券保持区间外。'}, {id:'missing',type:'MISSING',label:'资料缺口',tone:'amber',company:'a',security:'SYN-A',market:'a',date:'09-30',title:'本交易日最终收盘价尚未取得',body:'当前待评估，保留最后已确认的区间内状态。'}, {id:'config',type:'CONFIG_CHANGE',label:'规则变更',tone:'blue',company:'b',security:'SYN-B',market:'a',date:'09-28',title:'新策略版本建立基线',body:'配置变化单独记录，不作为市场进入或退出。'}];
const can=(cap)=>roles[state.role]?.includes(cap);
const isPhone=()=>window.matchMedia('(max-width:750px)').matches;
const navs={business:[['changes','◷','今日变化'],['companies','▤','公司研究'],['strategy','◇','策略候选'],['watchlist','☆','我的自选']],admin:[['sources','▥','数据源'],['jobs','≋','运行任务'],['quality','△','数据质量'],['identity','▦','公司与证券'],['decisions','◎','分析复核'],['templates','▧','评分模板'],['strategy','◇','策略发布'],['models','◈','模型与费用'],['roles','♙','用户与权限'],['audit','≡','审计']]};
const routes={changes:renderChanges,change:renderChange,companies:renderCompanies,company:renderCompany,evidence:renderEvidence,decisions:renderDecision,templates:renderTemplates,strategy:renderStrategy,watchlist:renderWatchlist,sources:renderSources,jobs:renderJobs,quality:renderQuality,identity:renderIdentity,models:renderModels,roles:renderRoles,audit:renderAudit};
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3000);}
function dialog(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
function navigate(route){if(location.hash==='#'+route)render();else location.hash=route;}
function permission(title,body){return `<div class="panel empty"><h2>${title}</h2><p>${body}</p>${link('changes','回到今日变化')}</div>`;}
function currentRoute(){return (location.hash.slice(1)||'changes').split('/');}
function render(){
 const [route,arg]=currentRoute(); if(arg && ['company','decisions'].includes(route))state.company=arg==='b'?'b':'a';
 document.body.dataset.mode=state.mode;
 $('#nav').innerHTML=navs[state.mode].map(([path,icon,name])=>`<a class="nav-link ${route===path||(path==='companies'&&route==='company')?'active':''}" href="#${path}"><span class="nav-icon" aria-hidden="true">${icon}</span>${name}</a>`).join('');
 $('#business-mode').classList.toggle('selected',state.mode==='business');$('#admin-mode').classList.toggle('selected',state.mode==='admin');$('#role').value=state.role;
 const business=['changes','change','companies','company','evidence','watchlist','decisions','templates','strategy','identity'];
 let html=business.includes(route)&&!can('research.read')?permission('此身份没有研究资料查看权限','系统管理员可管理用户和连接，不隐式获得研究判断或策略发布权限。可从上方切换合成身份查看另一条用户路径。'):(routes[route]||renderChanges)(arg);
 const scenario=state.scenario;
 if(scenario==='loading')html=header('正在取得研究快照','保留页面结构，等待资料加载。')+panel('研究资料','<div class="skeleton"></div><div class="skeleton large"></div>'+btn('完成合成加载','finish-load'));
 else if(scenario==='empty')html=header('没有符合条件的结果','当前筛选范围没有可展示的记录。')+`<div class="panel empty"><h2>试试扩大筛选范围</h2><p>这里表示筛选无结果。尚未接入、资料不可见和确实没有变化是不同状态。</p>${btn('清除筛选','finish-load','primary')}</div>`;
 else if(scenario==='permission')html=permission('当前对象不可查看','可见范围已变化，页面不显示原文、分数或计数。请联系本组织管理员检查授权。');
 else if(scenario==='partial')html=notice('部分资料取得失败','示例制造的原文和经营分仍可查看；本日A股估值缺价，无法作新的入选判断。'+link('quality','查看受影响范围'))+html;
 if(scenario==='updated')html=notice('有新的研究结果','你正在看的快照继续保留。查看新结果后再更新页面，不突然替换正在阅读的内容。','info')+btn('查看新快照','finish-load')+html;
 if(scenario==='suspended')html=notice('证券已停牌','SYN-A 显示暂停并保留上次已确认状态；恢复后需重新确认，不产生重复进入记录。')+html;
 $('#main').innerHTML=html+`<div class="demo-controls"><strong>设计状态演示</strong><label for="scenario">页面状态</label><select id="scenario"><option value="normal">正常</option><option value="loading">加载</option><option value="empty">筛选无结果</option><option value="partial">部分失败</option><option value="permission">不可见</option><option value="conflict">编辑冲突</option><option value="missing">UNKNOWN / 重算等待</option><option value="updated">新版本提示</option><option value="suspended">停牌</option></select><span>原型状态用于讨论交互，不代表服务端验收。</span></div>`;
 $('#main').dataset.route=location.hash||'#changes';
 $('#scenario').value=state.scenario; $('#scenario').addEventListener('change',e=>{state.scenario=e.target.value;render();});
 bindForms();
}
function renderChanges(){
 const rows=changes.filter(c=>(state.market==='all'||c.market===state.market)&&(state.changeType==='all'||c.type===state.changeType));
 return header('今日变化','先看变化，再回到当时的规则和证据。')+`<div class="toolbar"><div class="filters"><label>日期 <select aria-label="日期"><option>2026-09-28 至 09-30 · 演练窗口</option></select></label>${['all','a','h'].map((x,i)=>btn(['全部市场','A 股','港股'][i],'market-'+x,'filter-button '+(state.market===x?'active':''))).join('')}</div><span class="quiet">演练包含 09-28 至 09-30 的固定快照</span></div><div class="summary-line"><div><strong>1</strong><span>新入选证券</span></div><div><strong>1</strong><span>明确挂牌风险</span></div><div><strong>1</strong><span>资料缺口</span></div><div><strong>2</strong><span>关注公司</span></div></div><div class="toolbar"><h2>值得查看的变化</h2><div class="filters"><label>变化类型 <select id="change-filter"><option value="all">全部变化</option><option value="ENTER">新入选</option><option value="RISK">风险</option><option value="MISSING">资料缺口</option><option value="CONFIG_CHANGE">规则变更</option></select></label></div></div><section class="panel">${rows.map(c=>`<article class="change-row"><div class="date">${c.date}<br>固定历史快照</div><div>${badge(c.label,c.tone)}<h3 style="margin-top:8px">${companies[c.company].name}</h3><p>${c.security}</p></div><div><h3>${c.title}</h3><p>${c.body}</p></div>${link('change/'+c.id,'查看依据')}</article>`).join('')||'<div class="empty">当前筛选没有变化。</div>'}</section><div class="flow-link">${link('company/a','从公司展开研究')}${link('decisions/a','查看自动判断与人工覆盖')}${link('strategy','查看策略候选')}</div>`;
}
function renderChange(id='enter'){
 const c=changes.find(x=>x.id===id)||changes[0];const isRisk=c.type==='RISK';const missing=c.type==='MISSING';
 return `<div class="breadcrumb">${link('changes','今日变化')} / 固定历史解释</div>`+header(c.title,`${companies[c.company].name}　${c.security}　记录日期 2026-${c.date}`,badge(c.label,c.tone))+notice('你正在看当时记录',isRisk?'本条只针对SYN-H主挂牌。拒绝此风险不会解除另一个公司级风险。':missing?'当日最终收盘价缺失，显示待评估，最后确认状态仍是区间内。':'当时规则和输入已经固定；后续模板、判断和价格变化不会改写本条解释。','info')+`<div class="split">${panel('当时为什么发生变化',`<dl class="definition"><dt>策略发布</dt><dd>标准价投候选 · 发布 1</dd><dt>证券范围</dt><dd>${c.security}，${isRisk?'只适用H挂牌':'按本证券市场独立评估'}</dd><dt>前后状态</dt><dd>${isRisk?'区间外 → 区间外，新增风险原因':missing?'区间内 → 待评估，保留已确认区间内':'区间外 → 区间内'}</dd><dt>经营分 / 覆盖</dt><dd>72.0 / 100%</dd><dt>估值分</dt><dd>${isRisk?'45.0':missing?'无有效资料':'68.0'}</dd><dt>依据</dt><dd>${link('evidence','查看合成原始披露')}</dd></dl>${!isRisk&&!missing?'<ul class="reason-list"><li>公司经营分 72.0 ≥ 70<span>覆盖度100%，必需维度有效</span></li><li>本证券估值分 68.0 ≥ 60<span>A股价格与同口径财务匹配，不使用H股价格</span></li><li>两个相邻有效FINAL session均满足<span>09-28、09-29；不是两次页面刷新</span></li></ul>':''}`)}${panel('查看当前与更正',`<p>历史解释回答“当时为什么”；公司档案回答“现在是什么”。</p><div class="actions">${link('company/'+c.company,'查看当前公司状态')}${link('quality','查看更正与资料缺口')}</div><div class="focus-note">${isRisk?'H挂牌退市不等于公司全部证券退市。':'后来修正s2的输入，也需要检查s4、s6后续依据，不直接改今天的状态。'}</div>`,'固定解释与当前状态分开')}</div>`;
}
function renderCompanies(){
 const list=Object.entries(companies).filter(([,c])=>!state.query||c.name.includes(state.query)||c.securities.some(s=>s.name.toLowerCase().includes(state.query.toLowerCase())));
 return header('公司研究','列表按经营主体组织。证券候选与估值在公司内按 A/H 分开。')+`<div class="toolbar"><label class="filters">查找 <input id="company-search" type="search" aria-label="查找公司" placeholder="公司名或 SYN-A" value="${esc(state.query)}"></label><span class="quiet">两家公司 · 三只合成证券</span></div><section class="panel table-wrap"><table><thead><tr><th>公司 / 行业</th><th>经营分</th><th>覆盖度</th><th>证券与状态</th><th>最近变化</th><th>研究</th></tr></thead><tbody>${list.map(([id,c])=>`<tr><td>${link('company/'+id,c.name)}<p>${c.sector}</p></td><td class="number">${c.quality}</td><td>${c.coverage}</td><td>${c.securities.map(s=>`${s.name} ${badge(s.state,s.tone)}`).join('<br>')}</td><td>${id==='a'?'H挂牌风险，A报价缺口':'连续确认 1/2'}</td><td>${link('company/'+id,'打开档案')}</td></tr>`).join('')||'<tr><td colspan="6">没有匹配公司，请修改搜索词。</td></tr>'}</tbody></table></section>`;
}
function renderCompany(id='a'){
 const c=companies[state.company];const missing=state.scenario==='missing'||state.judgmentStatus==='waiting';const tabs=['timeline','scores','finance','valuation','relations','notes'];const names=['时间线','评分解释','财务','证券估值','关系','笔记'];
 let body='';
 if(state.tab==='timeline')body=`<div class="wide-split">${panel('公司事件时间线',`<div class="timeline-row"><div class="time-label">09-30<br>发生时间</div><div>${badge('仅H挂牌风险','red')}<h3 style="margin-top:8px">合成H挂牌退市决定</h3><p>证据明确指向SYN-H主挂牌，SYN-A不因这一风险改变状态。</p>${link('evidence','查看原始披露')}<div class="actions">${btn('查看风险判断','risk-detail','text-button')}</div></div></div><div class="timeline-row"><div class="time-label">09-29<br>系统得知</div><div>${badge(state.judgmentStatus==='auto'?'自动接受':'人工覆盖',state.judgmentStatus==='auto'?'blue':'amber')}<h3 style="margin-top:8px">同一订单事实的多份材料已归并</h3><p>两份合成材料支持同一经济事实，只计一次影响。${state.judgmentStatus==='auto'?'自动影响判断为 +0.8。':'人工新判断已记录；依赖重算状态单独展示。'}</p><div class="actions">${link('evidence','展开支持与反驳证据')}${link('decisions/'+state.company,'查看 / 修改影响')}</div></div></div><div class="timeline-row"><div class="time-label">09-30<br>报告期间</div><div><h3>财务资料与治理rubric基准更新</h3><p>已吸收订单事实的基准不再叠加同一事件贡献。</p>${btn('查看经营分依据','tab-scores','text-button')}</div></div>`)}${panel('本次研究要点',`<ul class="reason-list"><li>公司经营分独立于挂牌价格<span>${c.quality}分，覆盖${c.coverage}</span></li><li>A/H估值与候选状态不同<span>SYN-A估值68.0；SYN-H估值45.0</span></li><li>自动判断可以被有权人员修正<span>无需逐项人工审批才能生效</span></li></ul>${link('templates','查看使用的三层模板')}`)}</div>`;
 else if(state.tab==='scores')body=panel('经营分如何形成',`<div class="split"><div>${c.dimensions.map(([dimension,n,v,w])=>`<div class="dimension-row"><span>${n}<small class="quiet"> ${Math.round(Number(w)*100)}%</small></span><div class="bar"><i style="width:${v}%"></i></div><div class="value">${Number(v).toFixed(1)}</div></div>`).join('')}<p class="footnote">条形图为固定合成样例，各字段从同一解释快照展示；页面没有评分引擎。</p></div><div><h3>展开治理与资本配置</h3><dl class="definition"><dt>原始基准</dt><dd>rubric及档位证据</dd><dt>事件贡献</dt><dd>按经济事实去重、半衰期和上限</dd><dt>口径来源</dt><dd>基础 → 制造业 → 企业差异</dd></dl><div class="actions">${btn('修订rubric档位','rubric-detail')}${link('templates','比较继承与覆盖')}</div></div></div>`,'总分、覆盖与缺口并列，不把未知显示为0');
 else if(state.tab==='valuation')body=panel('按证券查看估值',`<div class="tabs">${c.securities.map(s=>btn(s.name+' / '+s.market,'valuation-'+s.id,'filter-button '+(state.selectedSecurity===s.id?'active':''))).join('')}</div>${valuation(c.securities.find(s=>s.id===state.selectedSecurity)||c.securities[0])}`,'公司经营事实共享，报价、币种、分母与V独立');
 else if(state.tab==='finance')body=panel('财务与报告义务',`<div class="table-wrap"><table><thead><tr><th>指标</th><th>规范值</th><th>期间/口径</th><th>依据</th></tr></thead><tbody><tr><td>ROE TTM</td><td>12.0%</td><td>普通股归属利润 / 匹配权益</td><td>${link('evidence','定位表格单元')}</td></tr><tr><td>3年CFO / 净利润</td><td>0.96</td><td>三完整年度合并金额先求和再相除</td><td>${link('evidence','查看三年依据')}</td></tr><tr><td>净债务 / EBITDA</td><td>1.20</td><td>同口径、同币种；分母有效</td><td>${link('evidence','查看指标出处')}</td></tr></tbody></table></div><div class="focus-note">下一份应有报告按冻结报告义务判断。三年历史指标需要旧年度资料，不统一套180日过期。</div>`);
 else if(state.tab==='relations')body=panel('主体与挂牌关系',`<h3>${c.name}（经营主体）</h3><ul class="reason-list">${c.securities.map(s=>`<li>${s.name} / ${s.market}<span>${s.currency}报价，独立工具身份及主要挂牌；经营资料关联同一公司</span></li>`).join('')}</ul><p class="footnote">关系传播需要有效期和依据，不沿母子公司无限扩散。</p>${link('identity','查看主数据关系与来源')}`);
 else body=panel('研究笔记',`<form id="notes-form"><div class="form-group"><label for="note">我的私人笔记</label><textarea id="note" placeholder="记录你的研究疑问，默认仅本人可见">${esc(state.note)}</textarea><small>本原型只保存于内存；正式设计使用服务端修订与If-Match。</small></div>${'<button type="submit" class="primary">保存笔记</button>'}</form>`);
 if(state.company==='b'&&state.tab==='timeline')body=panel('示例设备事件时间线','<div class="timeline-row"><div class="time-label">09-29</div><div><h3>合成年度资料更新</h3><p>仅发行SYN-B一只A股证券。经营分76.0，估值64.0；当前相邻确认1/2。</p></div></div><p class="footnote">示例制造的H挂牌风险与企业模板差异不适用于本公司。</p>');
 return `<div class="breadcrumb">${link('companies','公司研究')} / ${c.name}</div>`+header(`<span class="company-identity"><span class="company-monogram">${c.name.slice(2,3)}</span><span>${c.name}<small>${c.sector}　经营主体 · 合成公司</small></span></span>`,(state.company==='a'?'经营分快照09-29；09-30 A报价缺口。历史记录与当前状态分别查看。':'经营分与估值快照09-29；当前相邻确认1/2。'),btn(state.watch.includes(c.securities[0].id)?'已加入自选':'加入自选','watch-toggle'))+(missing?notice('新判断已记录，依赖结果正在重算','旧经营分快照仅供历史比较，当前为待评估，不能把旧贡献当作新值已生效。'):'')+`<div class="split">${panel('公司经营质量',`<div class="score-overview"><div><div class="score-number">${missing?'—':c.quality}</div><p>${missing?'待评估':'经营分'}</p></div><div><strong>覆盖 ${missing?'待更新':c.coverage}</strong><p>分数与覆盖度必须一起看</p>${link('templates','查看评分口径')}</div></div>`)}${panel('证券状态',c.securities.map(s=>`<div class="toolbar" style="margin:8px 0"><div><strong>${s.name}</strong><small class="quiet">　${s.market} / ${s.currency}</small></div>${badge(missing?'待评估':s.state,missing?'amber':s.tone)}</div>`).join('')+'<p class="footnote">'+(state.company==='a'?'A/H估值独立；H挂牌风险不会传播到A证券。':'本公司仅SYN-B证券，企业模板差异不影响其他公司。')+'</p>')}</div><div class="tabs">${tabs.map((x,i)=>btn(names[i],'tab-'+x,state.tab===x?'active':'')).join('')}</div>${body}`;
}
function valuation(s){return `<dl class="definition"><dt>证券 / 币种</dt><dd>${s.name} / ${s.currency}</dd><dt>正式收盘</dt><dd>${s.price} ${s.currency}　2026-09-29</dd><dt>估值分</dt><dd><strong style="font-size:30px">${s.v}</strong></dd><dt>分母口径</dt><dd>同权普通股每股归属盈利；含冻结股本与FX引用</dd><dt>行情状态</dt><dd>${badge('该session最终价','green')} 不等于评估已封存</dd><dt>依据</dt><dd>${link('evidence','查看财务、行情和单位依据')}</dd></dl>`;}
function renderEvidence(){state.company='a';return `<div class="breadcrumb">${link('company/'+state.company,'公司研究')} / 原始证据</div>`+header('合成披露：订单与挂牌事项','出处、定位和支持范围与判断一起阅读。',link('decisions/'+state.company,'查看对应判断'))+`<div class="split">${panel('原文与定位',`<div class="document"><div class="document-meta">来源：本地合成披露源<br>发布时间 2026-09-29 15:55　系统获取 16:40　正文定位 第2段<br>材料修订：演练修订2　支持/反驳证据各自保留</div><p>以下为专用于交互设计的虚构披露：</p><p>示例制造披露一项订单安排，<mark>订单以分期执行和客户验收为条件，尚不能确认全部转化为利润</mark>。本条用于比较原自动影响 +0.8 与研究员修订 −0.2 的证据解释。</p><p>另一个独立合成监管决定仅指向<mark>SYN-H主要挂牌</mark>，未指向公司所有证券。不得从来源市场推断风险作用范围。</p><p>本材料包含支持与限制性事实。模型摘要不替代这段可定位原文。</p></div>`)}${panel('证据与判断',`<ul class="reason-list"><li>公司关联：示例制造<span>直接主体；关联度与判断可信程度独立</span></li><li>订单事实影响<span>同一经济事实，即使有多篇转载也只计一次贡献</span></li><li>挂牌风险<span>目标为SYN-H listing；传播到确切证券</span></li></ul><div class="actions">${link('decisions/a','修改影响判断')}${btn('查看挂牌风险','risk-detail')}</div>${btn('演示证据不可访问','evidence-revoke','text-button')}`)}</div>`;}
function renderDecision(){
 state.company='a';
 const kind=state.decisionKind;const impact=kind==='impact';const rubric=kind==='rubric';const risk=kind==='risk';const permitted=can('analysis.override');
 const label=impact?'订单事实 · 盈利质量影响':rubric?'资本配置 · rubric档位':'SYN-H挂牌退市风险';
 const record=state.decisionRecords[kind];const old=record.value;
 const newValue=impact?state.replacement:rubric?state.grade:'拒绝本风险';
 const waiting=record.status==='waiting'||state.scenario==='missing';
 return `<div class="breadcrumb">${link('company/'+state.company,'公司时间线')} / 判断详情与人工覆盖</div>`+header(label,'查看原文、旧值与完整新值，明确作用对象后直接保存。',badge(record.status==='auto'?'AUTO accepted':record.status==='released'?'覆盖已解除，等待重新评估':'HUMAN 有效覆盖',record.status==='auto'?'blue':'amber'))+`<div class="tabs">${['impact','rubric','risk'].map((x,i)=>btn(['影响值','rubric档位','硬风险'][i],'decision-'+x,kind===x?'active':'')).join('')}</div>`+(state.scenario==='conflict'?notice('判断已被另一位研究员更新','你的新值和理由保留在下方。当前服务器示例值已变化，比较后可基于新版本重试。','error'):'')+(waiting?notice('人工判断已保存，重算等待中','新判断优先于后续AUTO建议；公司评分和A/H评估尚未完成。'+(risk?'若仍有公司级违约，两只证券继续受风险影响。':''),'info'):'')+`<div class="split">${panel('原文依据',`<p>订单分期执行，需经客户验收，不能确认全部转化为利润。</p><div class="focus-note">${risk?'监管决定明确指向SYN-H主要挂牌；不存在把同公司A证券一并退市的依据。':rubric?'rubric档位按固定锚点与证据选择，未知不填中位数。':'修改影响是修改经营判断，不是预测股价。'}</div>${link('evidence','打开完整原文与证据定位')}<dl class="definition"><dt>主体</dt><dd>示例制造</dd><dt>作用范围</dt><dd>${risk?'仅SYN-H主挂牌':'公司经营评分；A/H共享经营事实，各自估值'}</dd><dt>生效方式</dt><dd>从本次实际知悉时点生效，不回填系统历史</dd><dt>有效期</dt><dd>合成演练至2026-10-31；到期固定cutoff重评</dd><dt>输入证据</dt><dd>本页合成披露第2段</dd></dl>`)}${panel('人工覆盖',`<div class="value-compare"><div class="value-box"><span>当前有效值</span><strong>${esc(old)}</strong><small>${state.scenario==='conflict'?'冲突：已有更新版本':'当前判断版本 '+record.generation}</small></div><div class="value-box"><span>准备修改为</span><strong>${esc(newValue)}</strong><small>新修订保留旧值与原因</small></div></div>${!permitted?notice('此角色只能查看','查看者、策略管理员与系统管理员不隐式拥有analysis.override。可切换研究员身份体验。'):''}<form id="override-form"><div class="form-group"><label for="replacement">${impact?'完整新影响值（−1 至 +1）':rubric?'新档位（0 至 4）':'明确动作'}</label>${impact?`<input id="replacement" name="replacement" type="number" min="-1" max="1" step="0.1" value="${esc(state.replacement)}" ${!permitted?'disabled':''}>`:rubric?`<select id="grade" ${!permitted?'disabled':''}>${[0,1,2,3,4].map(g=>`<option ${String(g)===state.grade?'selected':''}>${g}</option>`).join('')}</select>`:'<p>拒绝这一条确切挂牌风险；不按risk_code全公司清除。</p>'}<small>证据、主体、事实时期及其他完整字段沿用本页固定样例。改身份应新建判断。</small></div><div class="form-group"><label for="reason">修改理由</label><textarea id="reason" required placeholder="说明证据为什么支持新判断" ${!permitted?'disabled':''}>${esc(state.reason)}</textarea></div><div id="override-error" class="form-error" role="alert"></div><div class="actions"><button type="submit" class="primary" ${!permitted?'disabled':''}>${risk?'拒绝本风险':'保存人工覆盖'}</button></div></form>${record.status!=='auto'&&record.status!=='released'?`<div class="actions">${btn('查看合成重算结果','show-recompute')}${btn('解除人工覆盖','release-override','text-button',!permitted?'disabled':'')}</div>`:''}<p class="footnote">单项编辑不增加预览审批；正式服务验证If-Match与幂等键。原型仅演示交互。</p>`,'当前值、新值和证据并列')}</div>`;
}
function renderTemplates(){
 const editable=can('template.edit')&&!isPhone();const publish=can('template.publish')&&!isPhone();
 return header('三层评分模板','当前经营分沿用已发布企业方案；下方是客户留存扩展草稿，升级发布后才生效。',badge(state.templatePublished?'演示新版本已发布':'合成企业草稿','blue'))+`<div class="steps"><div class="step"><strong>通用基础 · v2</strong><span>注册维度、标准口径与权重</span></div><div class="step"><strong>制造业 · v2</strong><span>固定引用基础v2</span></div><div class="step active"><strong>示例制造 · 企业差异</strong><span>只影响这一家公司的经营评分</span></div></div>${!editable?notice(isPhone()?'手机查看模式':'当前角色仅查看模板',isPhone()?'复杂模板编辑与发布请到桌面完成。':'研究员或策略管理员可编辑；策略管理员才能发布。'):''}<section class="panel"><div class="panel-head"><div><h2>继承、覆盖与最终值</h2><p>证据和新鲜度也是模板内容，不只改权重。</p></div>${badge('客户留存维度 · 已注册可用','gray')}</div><div class="table-wrap"><table><thead><tr><th>配置项</th><th>继承值</th><th>企业覆盖</th><th>最终值与来源</th></tr></thead><tbody><tr><td>盈利质量权重</td><td>基础25% → 制造业30%</td><td>本扩展草稿未覆盖</td><td>30% · 制造业</td></tr><tr><td>治理rubric证据龄期</td><td>180日</td><td><label class="visually-hidden" for="template-age">企业证据龄期</label><select id="template-age" ${!editable?'disabled':''}><option ${state.templateAge==='90'?'selected':''}>90</option><option ${state.templateAge==='180'?'selected':''}>180</option></select> 日</td><td>${state.templateAge}日 · 企业；再与策略上限取严格门</td></tr><tr><td>证据要求</td><td>可访问原文</td><td>发行人 / 监管原文</td><td>发行人 / 监管原文 · 企业</td></tr><tr><td>完整草稿权重</td><td>30 / 20 / 25 / 15 / 10%</td><td>成长5%，客户留存5%</td><td>六维合计100%；当前已发布企业方案盈利35%、成长5%</td></tr><tr><td>客户留存维度</td><td>注册目录已提供，基础模板未启用</td><td>已注册样例；完整基准与权重</td><td>客户留存维度；由人维护注册</td></tr><tr><td>事件参与</td><td>接受事件</td><td><label class="visually-hidden" for="event-mode">事件参与方式</label><select id="event-mode" ${!editable?'disabled':''}><option value="enabled" ${state.eventMode==='enabled'?'selected':''}>接受事件 / H=90日</option><option value="disabled" ${state.eventMode==='disabled'?'selected':''}>仅基准</option></select></td><td>${state.eventMode==='enabled'?'可接受受限影响；半衰期90日':'拒绝该维度影响；无虚构零贡献'}</td></tr></tbody></table></div></section>${notice('120日龄证据的固定对照',state.templateAge==='90'?'90日模板下证据已过期：若为策略必需维度，评估UNKNOWN。原有180日的已发布策略继续使用原冻结口径。':'180日模板下年龄条件满足；还需满足原文权利与其他质量要求。','info')}<div class="actions">${btn('保存草稿','save-template','secondary',!editable?'disabled':'')}${btn('模拟与差异预览','preview-template','primary',!editable?'disabled':'')}${btn('还原继承','restore-template','text-button',!editable?'disabled':'')}</div>${state.templatePreview?panel('固定输入差异预览',`<p>受影响：示例制造1家公司，SYN-A / SYN-H两只证券。示例设备不受企业差异影响。</p><div class="preview-diff">${badge('旧口径：180日','gray')}<span>→</span>${badge('新口径：'+state.templateAge+'日','amber')}</div><p>${state.eventMode==='disabled'?'客户留存只按基准；事件影响不能落入这一维度。':'客户留存允许受限事件影响。'}</p><p class="footnote">仅展示固定场景对照，不运行模板解析/评分引擎。完整维度与权重示例见仓库examples/v03-template-custom.json。</p><div class="actions">${btn('发布新模板版本','publish-template','primary',!publish?'disabled':'')}</div>${!publish?'<p class="footnote">你可编辑与预览，发布由策略管理员完成。</p>':''}`):''}`;
}
function renderStrategy(){
 const allowed=can('strategy.publish')&&!isPhone();
 const rows=Object.values(companies).flatMap(c=>c.securities.map(s=>({c,s})));
 return header('标准价投候选','按证券评估；公司经营分与证券估值分分别展示。',badge(state.strategyPublished?'演示发布 2':'发布 1 · 固定口径','blue'))+`<section class="panel table-wrap"><table><thead><tr><th>公司 / 证券</th><th>经营分 / 覆盖</th><th>估值分</th><th>策略状态</th><th>关键原因</th></tr></thead><tbody>${rows.map(({c,s})=>`<tr><td>${link('company/'+(c.name==='示例制造'?'a':'b'),c.name)}<p>${s.name} / ${s.market}</p></td><td>${c.quality} / ${c.coverage}</td><td class="number">${s.v}</td><td>${badge(s.state,s.tone)}</td><td>${s.id==='a-h'?'V低于进入阈值，另有挂牌风险':s.id==='b-a'?'首个有效确认；1/2':'两相邻FINAL满足条件'}<p>${link(s.id==='a-h'?'change/risk':'change/enter','查看规则与依据')}</p></td></tr>`).join('')}</tbody></table></section>${panel('维护策略草稿',`<div class="form-grid"><div class="form-group"><label for="strategy-threshold">进入经营分阈值</label><select id="strategy-threshold" ${!allowed?'disabled':''}><option ${state.strategyThreshold==='70'?'selected':''}>70</option><option ${state.strategyThreshold==='75'?'selected':''}>75</option></select><small>退出维持阈值65、其他条件沿用固定样例。只提供有对照快照的两个演示选项。</small></div><div><h3>条件的业务解释</h3><p>经营分 ≥ ${state.strategyThreshold}，覆盖 ≥ 80%，证券估值 ≥ 60；财务指标与风险门保持。</p><p class="footnote">两相邻expected FINAL确认；UNKNOWN打断pending。</p></div></div>${!allowed?notice(isPhone()?'手机查看模式':'当前身份没有策略编辑/发布能力',isPhone()?'复杂规则编辑、模拟和发布请到桌面完成。':'研究员可覆盖判断，不能发布策略。切换策略管理员可体验模拟发布。'):''}<div class="actions">${btn('固定时点模拟','simulate-strategy','primary',!allowed?'disabled':'')}</div>`,'草稿改动使旧预览失效，发布不改旧版')}${state.strategyPreview?panel('模拟变化预览',`<div class="steps"><div class="step active"><strong>固定时点</strong><span>2026-09-29收盘输入</span></div><div class="step active"><strong>比较变化</strong><span>${state.strategyThreshold==='75'?'示例制造72不再满足进入条件':'沿用原进入阈值'}</span></div><div class="step"><strong>发布新基线</strong><span>标记CONFIG_CHANGE</span></div></div><table><thead><tr><th>证券</th><th>旧规则</th><th>新规则基线</th></tr></thead><tbody><tr><td>SYN-A</td><td>区间内</td><td>${state.strategyThreshold==='75'?'区间外 · CONFIG_CHANGE':'区间内 · 原规则符合'}</td></tr><tr><td>SYN-H</td><td>区间外</td><td>区间外 · 独立挂牌风险</td></tr><tr><td>SYN-B</td><td>待确认</td><td>新release按有效输入静默建基线，不生成市场ENTER</td></tr></tbody></table><p class="footnote">固定样例模拟结果，无实时策略计算；发布只更新原型版本标签。</p><div class="actions">${btn('确认发布新版本','publish-strategy','primary',!allowed?'disabled':'')}</div>`):''}${panel('发布历史与回滚','<p>发布1继续保留固定规则和历史解释。回滚应引用旧配置创建新release并重新预览，不覆盖发布1。</p>'+btn('查看回滚预览','rollback-preview','text-button',!allowed?'disabled':''))}`;
}
function renderWatchlist(){const securities=Object.entries(companies).flatMap(([id,c])=>c.securities.map(s=>({id,c,s}))).filter(x=>state.watch.includes(x.s.id));return header('我的自选','按证券保存，研究时可以回到同一公司档案。')+panel('关注证券',securities.length?`<div class="table-wrap"><table><thead><tr><th>公司 / 证券</th><th>经营分</th><th>证券状态</th><th>操作</th></tr></thead><tbody>${securities.map(({id,c,s})=>`<tr><td>${link('company/'+id,c.name)}<p>${s.name}</p></td><td>${c.quality}</td><td>${badge(s.state,s.tone)}</td><td>${btn('移出自选','unwatch-'+s.id,'text-button')}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h2>开始关注一个研究对象</h2><p>在公司档案选择“加入自选”。</p>${link('companies','查找公司')}</div>`);}
function adminPermission(cap,title){return !can(cap)?permission('此身份没有'+title+'权限','请切换对应合成角色查看管理交互。管理权限与业务覆盖/发布分别授予。'):null;}
function renderSources(){const denied=adminPermission('source.manage','数据源管理');if(denied)return denied;return header('数据源','先看采集范围、最近成功与业务影响，再展开技术诊断。')+panel('本地合成披露源',`<div class="toolbar"><h3>local-fixture</h3>${badge(state.sourcePaused?'已暂停':'已启用',state.sourcePaused?'amber':'green')}</div><dl class="definition"><dt>业务范围</dt><dd>两家公司，三只证券</dd><dt>权利状态</dt><dd>合成fixture，可读/保存/分析；不配置真实凭证</dd><dt>最近运行</dt><dd>${state.imported?'演示导入完成':'等待演示导入'}</dd><dt>下一计划</dt><dd>${state.sourcePaused?'暂停后不再创建run':'固定演练计划，不实际调度'}</dd></dl><div class="actions">${btn(state.imported?'查看导入结果':'导入合成资料','import-fixture','primary',state.sourcePaused?'disabled':'')}${btn(state.sourcePaused?'恢复计划':'暂停计划','toggle-source')}${link('jobs','查看采集任务')}</div>`)+panel('频率与范围说明','<p>真实源适配时再固定供应商、抓取/保存/模型分析/导出权利。配置发布可先预览请求量与回溯范围；常规草稿不逐项审批。</p>'+btn('查看配置发布预览','source-preview','text-button'));}
function renderJobs(){const denied=!(can('job.retry')||can('ops.read'));if(denied)return permission('仅运行管理身份可查看任务','数据管理员可以恢复失败项，系统管理员可以查看运行诊断。');return header('运行任务','失败项与受影响公司一起显示，不把失败冒充没有资料。')+panel('合成行情更新',`<div class="toolbar"><h3>SYN-A 正式收盘价</h3>${badge(state.jobRecovered?'演示恢复完成':'一项失败',state.jobRecovered?'green':'amber')}</div><dl class="definition"><dt>影响</dt><dd>${state.jobRecovered?'已取得固定样例，等待策略重评':'SYN-A 当前待评估，保留最后已确认区间内'}</dd><dt>原因</dt><dd>合成源本session暂缺最终价</dd><dt>恢复范围</dt><dd>只恢复这一session失败项，不重跑membership或历史转移</dd><dt>账本</dt><dd>沿用完整逻辑键与cutoff，丢ACK不重复生效</dd></dl><div class="actions">${btn('预览失败项恢复','retry-preview','primary',!can('job.retry')?'disabled':'')}${link('quality','查看业务影响')}${link('company/a','回到公司研究')}</div>`)+panel('导入与分析阶段','<div class="steps"><div class="step active"><strong>原文保存</strong><span>演示成功</span></div><div class="step active"><strong>判断保存</strong><span>自动接受 / 人工覆盖</span></div><div class="step"><strong>评分与评估</strong><span>按固定时点完成重算</span></div></div>');}
function renderQuality(){if(!(can('research.read')||can('ops.read')))return permission('无法查看质量影响','切换研究或运营身份查看合成对象。');return header('数据质量与更正','先确认影响什么业务，再选择恢复资料或纠正历史。')+panel('当前资料缺口',`<div class="toolbar"><div><h3>SYN-A缺少本日最终价</h3><p>只阻止本日评估推进，不表示公司没有研究资料。</p></div>${badge(state.jobRecovered?'演示已恢复':'待恢复','amber')}</div><div class="actions">${link('jobs','定位失败任务')}${link('change/missing','查看固定缺口解释')}</div>`)+panel('封存历史更正',`<p>合成s2输入错误，后续s4退出、s6进入各有独立依据。更正s2先重放受影响窗口，不直接把今天IN改OUT。</p><div class="steps"><div class="step"><strong>s2 当时进入</strong><span>保留原记录</span></div><div class="step"><strong>s4 后续退出</strong><span>检查是否仍成立</span></div><div class="step active"><strong>s6 独立进入</strong><span>当前IN保留</span></div></div><div class="actions">${btn('查看更正范围预览','correction-preview','secondary',!can('quality.correct')?'disabled':'')}</div>${state.correctionAdded?notice('已追加合成更正说明','当前状态仍IN，演示未删除旧ENTER/EXIT。','info'):''}<p class="footnote">现在新出现的知识从实际known_at生效，不借纠错回填历史。</p>`);}
function renderIdentity(){return header('公司与证券身份','主体、证券、挂牌三层分开；合并前先比较范围。')+panel('示例制造',`<div class="table-wrap"><table><thead><tr><th>经营主体</th><th>工具</th><th>主要挂牌</th><th>币种</th><th>作用范围</th></tr></thead><tbody><tr><td>示例制造</td><td>SYN-A / A类</td><td>合成A挂牌</td><td>CNY</td><td>独立估值和策略状态</td></tr><tr><td>同一公司</td><td>SYN-H / H类</td><td>合成H挂牌</td><td>HKD</td><td>挂牌退市仅匹配H</td></tr></tbody></table></div><div class="actions">${btn('主数据变更影响预览','identity-preview','secondary',!can('identity.manage')?'disabled':'')}</div><p class="footnote">旧主体ID与历史关系不删除，原历史评估继续引用原身份版本。</p>`);}
function renderModels(){const denied=adminPermission('model.configure','模型配置');if(denied)return denied;return header('模型与费用','先用mock模型贯通分析路径，记录用量和失败原因。')+panel('分析适配器',`<dl class="definition"><dt>当前模型</dt><dd>mock-fixture（无网络）</dd><dt>自动审核</dt><dd>固定auto-review-policy与校准引用；没有可用校准不能伪造可信程度</dd><dt>外部模型</dt><dd>目标能力已保留，真实接入另行实施</dd><dt>用量</dt><dd>0次真实请求 / 0实际token / 无采购</dd></dl><p>凭证只在正式受控配置中引用，不出现在本原型或Git。</p>`);}
function renderRoles(){const denied=adminPermission('role.assign','角色管理');if(denied)return denied;return header('用户与角色','五角色可兼任。系统管理能力与业务判断、发布能力分别授予。')+panel('合成研究员：示例成员',`<form id="roles-form"><div class="checkbox-list">${[['viewer','查看者'],['researcher','研究员'],['strategy_manager','策略管理员'],['data_admin','数据管理员'],['system_admin','系统管理员']].map(([v,n])=>`<label><input type="checkbox" name="roles" value="${v}" ${v==='researcher'?'checked':''}>${n}</label>`).join('')}</div><p class="quiet">本例只修改这一名合成成员；不允许无替代撤掉最后管理员。</p>${btn('查看权限差异','role-preview','primary')}</form>`)+`<div class="role-grid">${Object.entries(roles).filter(([x])=>x!=='lead').map(([r,caps])=>`<div class="role-card"><h3>${{viewer:'查看者',researcher:'研究员',strategy_manager:'策略管理员',data_admin:'数据管理员',system_admin:'系统管理员'}[r]}</h3><p>${caps.map(x=>({['research.read']:'研究读取',['analysis.override']:'人工覆盖',['template.edit']:'模板编辑',['template.publish']:'模板发布',['strategy.publish']:'策略发布',['source.manage']:'源管理',['job.retry']:'失败项重试',['quality.correct']:'质量纠错',['identity.manage']:'身份维护',['role.assign']:'角色分配',['model.configure']:'模型配置',['audit.read']:'审计读取',['ops.read']:'运行读取'}[x])).join('、')}</p></div>`).join('')}</div>`;}
function renderAudit(){const denied=adminPermission('audit.read','审计读取');if(denied)return denied;return header('操作记录','动作与对象修订可追溯，不展示凭证或原始私有日志。')+panel('合成演示记录',`<ul class="reason-list"><li>研究员修订影响值<span>旧修订保留；当前slot按generation指向新决定。</span></li><li>策略管理员发布固定规则<span>预览输入、父链及每家公司解析口径固定。</span></li><li>状态与outbox提交<span>正式实现必须同事务；此处只是设计样例。</span></li></ul>`);}
function bindForms(){
 const f=$('#change-filter');if(f){f.value=state.changeType;f.onchange=e=>{state.changeType=e.target.value;render();};}
 const search=$('#company-search');if(search)search.oninput=e=>{state.query=e.target.value;const p=e.target.selectionStart;render();const n=$('#company-search');n.focus();n.setSelectionRange(p,p);};
 const replacement=$('#replacement');if(replacement)replacement.oninput=e=>{state.replacement=e.target.value;};
 const grade=$('#grade');if(grade)grade.onchange=e=>{state.grade=e.target.value;};
 const reason=$('#reason');if(reason)reason.oninput=e=>{state.reason=e.target.value;};
 const form=$('#override-form');if(form)form.onsubmit=e=>{e.preventDefault();if(!can('analysis.override'))return;const err=$('#override-error');if(!state.reason.trim()){err.textContent='请写明修改理由，便于回查证据。';return;}if(state.decisionKind==='impact'&&(state.replacement===''||!Number.isFinite(Number(state.replacement))||Number(state.replacement)<-1||Number(state.replacement)>1)){err.textContent='影响值须为−1至+1之间的数值。';return;}if(state.scenario==='conflict'){err.innerHTML='示例409：你的草稿保留。'+btn('比较并采用新版本重试','resolve-conflict','text-button');return;}const record=state.decisionRecords[state.decisionKind];record.value=state.decisionKind==='impact'?state.replacement:state.decisionKind==='rubric'?state.grade:'人工拒绝本挂牌风险';record.status='waiting';record.generation++;state.judgmentStatus='waiting';state.generation++;render();toast('合成人工修订已保存，依赖重算等待中');};
 const nform=$('#notes-form');if(nform)nform.onsubmit=e=>{e.preventDefault();state.note=$('#note').value;toast('笔记保存在本次原型内存中');};
 const age=$('#template-age');if(age)age.onchange=e=>{state.templateAge=e.target.value;state.templatePreview=false;state.templatePublished=false;render();};
 const mode=$('#event-mode');if(mode)mode.onchange=e=>{state.eventMode=e.target.value;state.templatePreview=false;render();};
 const threshold=$('#strategy-threshold');if(threshold)threshold.onchange=e=>{state.strategyThreshold=e.target.value;state.strategyPreview=false;render();};
 const rform=$('#roles-form');if(rform)rform.onsubmit=e=>e.preventDefault();
}
document.addEventListener('click',e=>{
 const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const action=el.dataset.action;
 if(action.startsWith('tab-')){state.tab=action.slice(4);render();}
 else if(action.startsWith('market-')){state.market=action.slice(7);render();}
 else if(action.startsWith('decision-')){state.decisionKind=action.slice(9);render();}
 else if(action.startsWith('valuation-')){state.selectedSecurity=action.slice(10);render();}
 else if(action.startsWith('unwatch-')){state.watch=state.watch.filter(x=>x!==action.slice(8));render();}
 else if(action==='watch-toggle'){const id=companies[state.company].securities[0].id;state.watch=state.watch.includes(id)?state.watch.filter(x=>x!==id):[...state.watch,id];render();toast('自选更新仅保留在原型内存');}
 else if(action==='risk-detail'||action==='rubric-detail'){state.decisionKind=action==='risk-detail'?'risk':'rubric';navigate('decisions/'+state.company);}
 else if(action==='finish-load'){state.scenario='normal';state.market='all';state.changeType='all';render();}
 else if(action==='evidence-revoke'){dialog('<h2>原文现已不可访问</h2><p>权利已撤销或到期，保留引用与不可访问原因，不返回缓存正文。当前依赖评分需要重新检查覆盖度。</p><p class="footnote">此弹窗演示正式页面状态，不执行真实撤权。</p>');}
 else if(action==='show-recompute'){state.scenario='normal';dialog('<h2>合成重算结果对照</h2><p>新判断已记录为人工有效值。实际重算应返回同一快照的经营分、覆盖与A/H评估。</p><p>本原型没有Decimal评分或状态机，仅展示“判断已保存”与“计算已完成”两个阶段。</p>');}
 else if(action==='release-override'){if(!can('analysis.override'))return;state.decisionRecords[state.decisionKind].status='released';state.decisionRecords[state.decisionKind].value='无有效判断，待重评';state.judgmentStatus='waiting';state.generation++;dialog('<h2>人工覆盖已解除（合成）</h2><p>当前等待固定cutoff的新合法判断；不恢复过期AUTO。拒绝风险与解除覆盖是不同动作。</p>');render();}
 else if(action==='resolve-conflict'){state.scenario='normal';state.generation++;state.decisionRecords[state.decisionKind].generation++;render();toast('已载入新版本，你的新值和理由仍保留；可重试保存');}
 else if(action==='save-template'){if(!can('template.edit'))return;state.templateDraft=true;toast('合成模板草稿已保存，尚未发布');}
 else if(action==='preview-template'){if(!can('template.edit'))return;state.templatePreview=true;render();}
 else if(action==='restore-template'){state.templateAge='180';state.eventMode='enabled';state.templatePreview=false;render();}
 else if(action==='publish-template'){if(!can('template.publish')||!state.templatePreview)return;state.templatePublished=true;state.templatePreview=false;render();toast('演示新模板发布；旧release继续固定旧口径');}
 else if(action==='simulate-strategy'){if(!can('strategy.publish'))return;state.strategyPreview=true;render();}
 else if(action==='publish-strategy'){if(!can('strategy.publish')||!state.strategyPreview)return;state.strategyPublished=true;state.strategyPreview=false;render();toast('演示发布2，变化分类CONFIG_CHANGE');}
 else if(action==='rollback-preview'){dialog('<h2>回滚提案预览</h2><p>引用发布1配置，创建新的发布3；原发布2与历史解释保留。受影响证券仍为SYN-A、SYN-H、SYN-B。</p><p class="footnote">这里只查看设计提案，不执行发布。</p>');}
 else if(action==='toggle-source'){if(!can('source.manage'))return;state.sourcePaused=!state.sourcePaused;render();}
 else if(action==='import-fixture'){if(!can('source.manage'))return;state.imported=true;toast('合成导入结果演示已就绪，未运行采集');navigate('jobs');}
 else if(action==='source-preview'){dialog('<h2>配置发布预览</h2><p>范围为两家公司、三只证券；本地合成fixture，无网络请求和采购。正常接入时再明确回溯期、请求量、权利和恢复方法。</p>');}
 else if(action==='retry-preview'){if(!can('job.retry'))return;dialog('<h2>只恢复一个失败项</h2><p>对象：SYN-A / 2026-09-30最终行情。沿用固定cutoff和业务键，不重跑历史membership。</p><div class="actions">'+btn('确认合成恢复','confirm-retry','primary')+'</div>');}
 else if(action==='confirm-retry'){if(!can('job.retry'))return;state.jobRecovered=true;$('#dialog').close();render();toast('固定恢复结果已展示；未调用源或任务服务');}
 else if(action==='identity-preview'){dialog('<h2>主数据变更影响预览</h2><p>示例制造关联两只证券、一个策略release及当前研究判断。身份修改需要固定旧/新映射、generation和证据；历史引用保留。</p><p class="footnote">本轮只展示范围，未提出真实合并对象。</p>');}
 else if(action==='correction-preview'){if(!can('quality.correct'))return;dialog('<h2>历史更正范围</h2><p>s2原输入错误；s4/s6仍有独立有效依据。窗口重放后当前IN保持，追加CORRECTION说明。</p><div class="actions">'+btn('追加合成更正说明','confirm-correction','primary')+'</div>');}
 else if(action==='confirm-correction'){if(!can('quality.correct'))return;state.correctionAdded=true;$('#dialog').close();render();}
 else if(action==='role-preview'){if(!can('role.assign'))return;const checked=[...document.querySelectorAll('input[name="roles"]:checked')].map(x=>x.value);dialog('<h2>合成成员的权限差异</h2><p>当前：研究员。</p><p>准备设为：'+esc(checked.join('、')||'无业务角色')+'。</p><p>只改变这一名成员，下一请求和后台提交按新能力检查。此示例不移除最后管理员。</p><div class="actions">'+btn('保存合成角色组合','confirm-role','primary')+'</div>');}
 else if(action==='confirm-role'){if(!can('role.assign'))return;state.roleChanges=true;$('#dialog').close();toast('角色组合仅作原型演示，未修改真实权限');}
});
$('#role').onchange=e=>{state.role=e.target.value;state.scenario='normal';if(state.role==='system_admin'){state.mode='admin';navigate('roles');}else if(state.role==='data_admin'){state.mode='admin';navigate('sources');}else{state.mode='business';render();}};
$('#business-mode').onclick=()=>{state.mode='business';navigate('changes');render();};
$('#admin-mode').onclick=()=>{state.mode='admin';navigate(can('source.manage')?'sources':can('role.assign')?'roles':can('analysis.override')?'decisions':can('template.edit')?'templates':'quality');render();};
$('#global-search').onkeydown=e=>{if(e.key==='Enter'){state.query=e.target.value;state.mode='business';navigate('companies');}};
$('#reset').onclick=()=>{state=initial();$('#global-search').value='';if($('#dialog').open)$('#dialog').close();navigate('changes');render();toast('已重置合成演示');};
$('#close-dialog').onclick=()=>$('#dialog').close();
window.matchMedia('(max-width:750px)').addEventListener('change',()=>render());
window.addEventListener('hashchange',()=>{render();$('#main').focus({preventScroll:true});window.scrollTo(0,0);});
render();
